import AuthProvider from '@/SessionProvider'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Donut Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
       
        <div className='container'>
          <Navbar />
        {children}
        <Footer />
        </div>

        </AuthProvider>        
      </body>
    </html>
  )
}
